import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { AnalysisSession } from '../types';
import { computeScore, getScoreLabel } from './score';

export function generatePdf(session: AnalysisSession): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // ---- Header ----
  doc.setFontSize(22);
  doc.setTextColor(99, 102, 241); // indigo accent
  doc.text('ReviewReply AI', 14, y);
  y += 8;

  doc.setFontSize(12);
  doc.setTextColor(100, 100, 100);
  doc.text('Analysis Report', 14, y);
  y += 10;

  // Business name + date
  doc.setFontSize(10);
  doc.setTextColor(60, 60, 60);
  doc.text(`Business: ${session.businessName}`, 14, y);
  doc.text(
    `Date: ${new Date(session.createdAt).toLocaleDateString(undefined, { dateStyle: 'long' })}`,
    pageWidth - 14,
    y,
    { align: 'right' }
  );
  y += 6;

  // Divider
  doc.setDrawColor(200, 200, 200);
  doc.line(14, y, pageWidth - 14, y);
  y += 10;

  // ---- Reputation Score ----
  const score = computeScore(session.sentimentSummary);
  const label = getScoreLabel(score);

  doc.setFontSize(14);
  doc.setTextColor(30, 30, 30);
  doc.text('Reputation Score', 14, y);
  y += 8;

  doc.setFontSize(28);
  if (score >= 70) doc.setTextColor(16, 185, 129);
  else if (score >= 45) doc.setTextColor(245, 158, 11);
  else doc.setTextColor(239, 68, 68);
  doc.text(`${score}/100`, 14, y);

  doc.setFontSize(14);
  doc.text(label, 55, y);
  y += 12;

  // ---- Sentiment Summary ----
  doc.setFontSize(14);
  doc.setTextColor(30, 30, 30);
  doc.text('Sentiment Summary', 14, y);
  y += 8;

  const s = session.sentimentSummary;
  autoTable(doc, {
    startY: y,
    head: [['Metric', 'Count', 'Percentage']],
    body: [
      ['Positive', `${s.positive}`, `${s.positivePercent}%`],
      ['Neutral', `${s.neutral}`, `${s.neutralPercent}%`],
      ['Negative', `${s.negative}`, `${s.negativePercent}%`],
      ['Total', `${s.total}`, '100%'],
    ],
    theme: 'grid',
    headStyles: { fillColor: [99, 102, 241] },
    margin: { left: 14, right: 14 },
  });

  // Get the final Y position after the table
  y = ((doc as unknown as Record<string, Record<string, number>>).lastAutoTable)?.finalY ?? y + 40;
  y += 12;

  // ---- Reviews Table ----
  if (y > 240) {
    doc.addPage();
    y = 20;
  }

  doc.setFontSize(14);
  doc.setTextColor(30, 30, 30);
  doc.text('Reviews & Responses', 14, y);
  y += 8;

  const reviewRows = session.results
    .filter(r => !r.error)
    .map(r => [
      r.reviewText.length > 80 ? r.reviewText.slice(0, 80) + '...' : r.reviewText,
      r.sentiment.toUpperCase(),
      r.reply.length > 80 ? r.reply.slice(0, 80) + '...' : r.reply,
    ]);

  autoTable(doc, {
    startY: y,
    head: [['Review', 'Sentiment', 'Reply']],
    body: reviewRows,
    theme: 'striped',
    headStyles: { fillColor: [99, 102, 241] },
    columnStyles: {
      0: { cellWidth: 60 },
      1: { cellWidth: 25 },
      2: { cellWidth: 80 },
    },
    margin: { left: 14, right: 14 },
    styles: { fontSize: 8, cellPadding: 3 },
  });

  y = ((doc as unknown as Record<string, Record<string, number>>).lastAutoTable)?.finalY ?? y + 40;
  y += 12;

  // ---- Improvements ----
  if (session.improvements.length > 0) {
    if (y > 240) {
      doc.addPage();
      y = 20;
    }

    doc.setFontSize(14);
    doc.setTextColor(30, 30, 30);
    doc.text('Suggested Improvements', 14, y);
    y += 8;

    const impRows = session.improvements.map(imp => [
      imp.category,
      `${imp.mentionCount}`,
      imp.suggestion,
    ]);

    autoTable(doc, {
      startY: y,
      head: [['Category', 'Mentions', 'Suggestion']],
      body: impRows,
      theme: 'striped',
      headStyles: { fillColor: [99, 102, 241] },
      margin: { left: 14, right: 14 },
      styles: { fontSize: 9 },
    });
  }

  // ---- Footer ----
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Generated by ReviewReply AI | ${new Date().toLocaleDateString()}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
    doc.text(
      `Page ${i} of ${pageCount}`,
      pageWidth - 14,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'right' }
    );
  }

  // ---- Download ----
  const filename = `${session.businessName.replace(/[^a-zA-Z0-9_-]/g, '_')}-report-${new Date().toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);
}
